Repository alskdteam/semi_project_java, pull requests merged in 2024-05, with the labels that each got.

#28 add admin_page -> css,html
  src/main/resources/static/css/admin.css
  src/main/resources/static/css/profile.css
  src/main/resources/static/css/qwer.css
  src/main/resources/templates/admin/admin.html
  src/main/resources/templates/subpage/car.html
Labels: documentation, feature, devolop

#53 차량페이지 모달창 값 데이터베이스에 전달
  src/main/java/com/ohgiraffers/semi_project/subpage/car/controller/CarController.java
  src/main/java/com/ohgiraffers/semi_project/subpage/car/model/dto/CarJoinDTO.java
  src/main/java/com/ohgiraffers/semi_project/subpage/car/model/dto/RegistDTO.java
  src/main/resources/mapper/car/carMapper.xml
  src/main/resources/static/css/car_situation.css
  src/main/resources/static/js/carSituation.js
  src/main/resources/templates/subpage/car.html
  src/main/resources/templates/subpage/car_situation.html
Labels: documentation, feature, devolop

#63 차량대여현황페이지에서 내예약 조회
  src/main/java/com/ohgiraffers/semi_project/subpage/car/controller/CarSituationController.java
  src/main/java/com/ohgiraffers/semi_project/subpage/car/model/dao/carMapper.java
  src/main/java/com/ohgiraffers/semi_project/subpage/car/model/service/CarService.java
  src/main/resources/mapper/car/carMapper.xml
  src/main/resources/static/js/carSituation.js
  src/main/resources/templates/subpage/car_situation_mypage.html
Labels: documentation, feature, devolop

#71 거래처관리 조회, 모달창 이용 거래처등록
  src/main/java/com/ohgiraffers/semi_project/subpage/account/controller/AccountController.java
  src/main/java/com/ohgiraffers/semi_project/subpage/account/model/dao/accountMapper.java
  src/main/java/com/ohgiraffers/semi_project/subpage/account/model/dto/AccountDTO.java
  src/main/java/com/ohgiraffers/semi_project/subpage/account/model/dto/AccountJoinDTO.java
  src/main/java/com/ohgiraffers/semi_project/subpage/account/model/dto/EmployeeDTO.java
  src/main/java/com/ohgiraffers/semi_project/subpage/account/model/dto/RegistAccDTO.java
  src/main/java/com/ohgiraffers/semi_project/subpage/account/model/service/AccountService.java
  src/main/resources/mapper/account/accountMapper.xml
  src/main/resources/static/css/account.css
  src/main/resources/templates/subpage/account.html
Labels: documentation, enhancement, feature, devolop

#86 프로필페이지 프로필 추가 기능 업데이트(insert+update) 및 프로필 전체 페이지 select 컨트롤러
  src/main/java/com/ohgiraffers/semi_project/subpage/profile/controller/ProfileController.java
  src/main/java/com/ohgiraffers/semi_project/subpage/profile/controller/ProfileEditController.java
  src/main/java/com/ohgiraffers/semi_project/subpage/profile/model/dao/ProfileMapper.java
  src/main/java/com/ohgiraffers/semi_project/subpage/profile/model/dto/ProfileDTO.java
  src/main/java/com/ohgiraffers/semi_project/subpage/profile/model/service/ProfileService.java
  src/main/resources/mapper/profile/ProfileEditMapper.xml
  src/main/resources/mapper/profile/ProfileSelect.xml
  src/main/resources/static/css/profile.css
  src/main/resources/templates/subpage/edocFrom/selectEdocList2.html
  src/main/resources/templates/subpage/profile.html
Labels: feature, devolop
